### PR TITLE
import `plink-ng` as a git dependency

### PR DESCRIPTION
**Pull request by aryarm**
Compared to VCFs, PLINK files are a much more efficient format for storing and working with GWAS datasets. Reading from PLINK files takes seconds, while I've estimated that reading from VCFs can take half an hour for even the small datasets we want to work with. We'll eventually want to list [the Python API for `plink-ng` (aka `pgenlib`)](https://github.com/chrchang/plink-ng/tree/master/2.0/Python) as a dependency of this tool, so that we can properly support reading and writing PLINK files. Currently [our code](https://github.com/aryarm/haptools/blob/9cb573c09d5f94f65c120af992888fa3df33103f/haptools/data/genotypes.py#L286) just assumes this dependency is installed instead of installing it automatically via `poetry`.

Unfortunately, `pgenlib` has not yet been published to PyPi, so we'll have to install it directly from the Github repo in the subdirectory that it lives in. `poetry-core` added support for installing git packages from subdirectories in [v1.1.0a7](https://github.com/python-poetry/poetry-core/releases/tag/1.1.0a7) (yesterday, on 3/5/22). So this PR adds `pgenlib` to the pyproject.toml file using the new syntax and updates `poetry` and `poetry-core` to support installing it.

### CODE REVIEW

**Comment by aryarm** [comment]
Looks like the readthedocs build failed because https://github.com/python-poetry/poetry-core/pull/300 hasn't been merged in yet.

The git url gets resolved to this
```
git+https://github.com/chrchang/plink-ng.git@v2.00a3-20220218#subdirectory2.0/Python
```
instead of this
```
git+https://github.com/chrchang/plink-ng.git@v2.00a3-20220218#subdirectory=2.0/Python
```
(notice the equal sign after `#subdirectory`?)

**Comment by maresb** [comment]
Ah, cool! I'm glad you found my patch useful.

Based on the result of `conda search -c conda-forge/label/poetry_dev "poetry-core>1.1.0a7"` it seems that it's already on Conda-Forge.

Since the dev branch isn't on the main Conda-Forge channel, you should follow [these instructions](https://github.com/conda-forge/poetry-feedstock/issues/57#issuecomment-1022805023).

BTW, you could have gotten a quicker response by opening an issue in the poetry-core-feedstock repository. (I just did this randomly because I noticed that a new version came out.)

**Comment by maresb** [comment]
I realize that those instructions are really obscure, so I just opened https://github.com/conda-forge/poetry-core-feedstock/issues/28 in order to make them easier to find.

**Comment by aryarm** [comment]
Yes, thank you for the patch, @maresb! And thanks for extracting those instructions to a place that's easier to find.


> a quicker response by opening an issue in the poetry-core-feedstock repository

This issue really isn't a priority for us, so I was willing to wait until someone decided to update the feedstock randomly! But thanks again for pinging me here to let me know it's available now. I'll see if I can merge this PR soon.

**Comment by aryarm** [comment]
I just rebased

but it looks like we'll still need https://github.com/python-poetry/poetry-core/pull/300 in order to get this to work :(

**Comment by aryarm** [comment]
closing in favor of #68

**Pull request closed without merging**
